scss_files:
  - 'app/assets/stylesheets/**'
exclude:
  - 'app/assets/stylesheets/application.css'
  - 'app/assets/stylesheets/animate.css'
  - 'vendor/assets/**'
linters:
  ImportantRule:
    enabled: true
  MergeableSelector:
    enabled: true
  UrlFormat:
    enabled: true
  StringQuotes:
    enabled: true
    style: double_quotes
  IdSelector:
    enabled: true
  NestingDepth:
    enabled: true
  SelectorDepth:
    enabled: true
